from .benchmark import FAKEWORK as FAKEWORK
from .benchmark import FFT as FFT
from .benchmark import HPCG as HPCG
from .benchmark import JA as JA
from .benchmark import LULESH as LULESH
from .benchmark import MW as MW
from .benchmark import NAS_BT as NAS_BT
from .benchmark import NAS_CG as NAS_CG
from .benchmark import NAS_EP as NAS_EP
from .benchmark import NAS_FT as NAS_FT
from .benchmark import NAS_IS as NAS_IS
from .benchmark import NAS_LU as NAS_LU
from .benchmark import NAS_MG as NAS_MG
from .benchmark import NAS_SP as NAS_SP
from .benchmark import NAS_UA as NAS_UA
from .benchmark import NONE as NONE
from .benchmark import PARBOIL_SPMV as PARBOIL_SPMV
from .benchmark import PO as PO
from .benchmark import RODINIA_BFS as RODINIA_BFS
from .benchmark import RODINIA_HOTSPOT as RODINIA_HOTSPOT
from .benchmark import RODINIA_HOTSPOT3D as RODINIA_HOTSPOT3D
from .benchmark import RODINIA_SRAD_V1 as RODINIA_SRAD_V1
from .benchmark import RODINIA_SRAD_V2 as RODINIA_SRAD_V2
from .benchmark import RODINIA_STREAMCLUSTER as RODINIA_STREAMCLUSTER
from .benchmark import ST as ST
from .fletcher import Fletcher as Fletcher
from .program import Program as Program
