from typing import Any
from . import (
    Plotter,
    SobolOrderResult,
    SI_PREFIX_FACTORS,
    DEFAULT_PARAM_UNITS,
    parse_unit_spec,
    _is_integer_range,
    get_unit,
    get_unit_converter,
    get_axis_label,
    to_real_clk,
    convert_clk_series,
    convert_clk_df,
    pad_to_even_and_split,
    mostly_square_grid,
    get_machine,
    get_axis_bounds,
    get_result_params,
    colors_for,
    key_for,
    get_distinct_colors,
    distinct_colors,
    get_n_distinct_colors,
    get_sobols_up_to_order,
    plot_sobols,
    plot_sobols1,
    sobols_up_to_order,
    sobols_of_up_to_order_n,
    plot_sobols_up_to_order,
    plot_sobols_order_n,
    plot_sobols_n,
    plot_grid_2D,
    plot_grid_2D_best,
    plot_sorted,
    plot_2D_single_dimension,
    plot_boxplot,
    draw_gradients,
    plot_stat_convergence,
    plot_adaptation_histogram,
    plot_adaptation_table,
    PlotterUnitsMixin,
    PlotterLayoutMixin,
    PlotterGridMixin,
    PlotterSobolMixin,
    PlotterDiagnosticsMixin,
)

_default_plotter = Plotter()


def init(mach: Any, units: Any = None, active_params: Any = None) -> Plotter:
    """Initialize default plotter module instance for the given machine."""
    _default_plotter.init(mach, units=units, active_params=active_params)
    return _default_plotter


from ..util.multi_plot import (
    plot_multi_sobols,
    plot_multi_convergence,
    plot_multi_energy_time_pareto,
    plot_multi_qoi_distribution,
    plot_multi_best_configurations,
    plot_multi_parameter_effects,
    plot_multi_dashboard,
)

__all__ = [
    "Plotter",
    "SobolOrderResult",
    "SI_PREFIX_FACTORS",
    "DEFAULT_PARAM_UNITS",
    "parse_unit_spec",
    "_is_integer_range",
    "get_unit",
    "get_unit_converter",
    "get_axis_label",
    "to_real_clk",
    "convert_clk_series",
    "convert_clk_df",
    "pad_to_even_and_split",
    "mostly_square_grid",
    "get_machine",
    "get_axis_bounds",
    "get_result_params",
    "colors_for",
    "key_for",
    "get_distinct_colors",
    "distinct_colors",
    "get_n_distinct_colors",
    "init",
    "get_sobols_up_to_order",
    "plot_sobols",
    "plot_sobols1",
    "sobols_up_to_order",
    "sobols_of_up_to_order_n",
    "plot_sobols_up_to_order",
    "plot_sobols_order_n",
    "plot_sobols_n",
    "plot_grid_2D",
    "plot_grid_2D_best",
    "plot_sorted",
    "plot_2D_single_dimension",
    "plot_boxplot",
    "draw_gradients",
    "plot_stat_convergence",
    "plot_adaptation_histogram",
    "plot_adaptation_table",
    "PlotterUnitsMixin",
    "PlotterLayoutMixin",
    "PlotterGridMixin",
    "PlotterSobolMixin",
    "PlotterDiagnosticsMixin",
    "plot_multi_sobols",
    "plot_multi_convergence",
    "plot_multi_energy_time_pareto",
    "plot_multi_qoi_distribution",
    "plot_multi_best_configurations",
    "plot_multi_parameter_effects",
    "plot_multi_dashboard",
]
